# Generated by Django 5.0.6 on 2024-07-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_phone_client_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='isregistred',
            new_name='adresse',
        ),
    ]
