# Generated by Django 5.0.6 on 2024-07-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_sales_service_project_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='information',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
