# Generated by Django 5.0.6 on 2024-07-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_isregistred_client_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adresse',
            new_name='isregistred',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='telephone',
            new_name='phone',
        ),
    ]
