# Generated by Django 5.0.6 on 2024-07-23 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_adresse_client_isregistred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.project'),
            preserve_default=False,
        ),
    ]
