# Generated by Django 5.0.6 on 2024-07-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_alter_project_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
