# Generated by Django 5.0.6 on 2024-07-28 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_client_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='service',
            new_name='services',
        ),
        migrations.AddField(
            model_name='project',
            name='srv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.service'),
            preserve_default=False,
        ),
    ]
