# Generated by Django 5.0.6 on 2024-07-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_service_project_services_project_srv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('datec', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.service')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
