# Generated by Django 5.0.6 on 2024-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='nbrView',
            field=models.IntegerField(default=0),
        ),
    ]
