# Generated by Django 5.0.6 on 2024-08-01 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_projects_nbrview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='nbrView',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datec', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.projects')),
            ],
        ),
    ]
