# Generated by Django 5.0.6 on 2024-08-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_projects_nbrview_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
