# Generated by Django 5.0.6 on 2024-08-03 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_comment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerPrj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('datec', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.projects')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
