# Generated by Django 5.0.6 on 2024-08-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customerprj'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Formateur', 'Formateur'), ('Autre', 'Autre')], default='Etudiant', max_length=50),
        ),
    ]
